# Generated by Django 5.1.6 on 2025-02-22 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grades', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grade',
            name='grade_number',
            field=models.CharField(max_length=10, unique=True, verbose_name='班级编号'),
        ),
    ]
